java SplitReviews "Nokia 6610.txt"
java SplitReviews "Nikon coolpix 4300.txt"
java SplitReviews "Creative Labs Nomad Jukebox Zen Xtra 40GB.txt"
java SplitReviews "Canon G3.txt"
java SplitReviews "Apex AD2600 Progressive-scan DVD player.txt"
