java SplitReviews "Canon PowerShot SD500.txt"
java SplitReviews "Canon S100.txt"
java SplitReviews "Diaper Champ.txt"
java SplitReviews "Hitachi router.txt"
java SplitReviews "ipod.txt"
java SplitReviews "Linksys Router.txt"
java SplitReviews "MicroMP3.txt"
java SplitReviews "Nokia 6600.txt"
java SplitReviews "norton.txt"